-- ============================================
-- DEPRECATED — DO NOT USE
-- ============================================
--
-- Este archivo contenía los planes del estudio anterior. El catálogo
-- de producción de Sunrise Sunset se gestiona vía:
--
--   database/seeds/sunrise_class_types.sql   (3 tipos de clase)
--   database/seeds/sunrise_packages.sql      (12 paquetes con credit buckets)
--   database/seeds/sunrise_singles.sql       (muestra + sueltas + inscripción +
--                                             desactivación de planes legacy)
--
-- Aplica esos tres archivos en orden después de `schema_complete.sql` o
-- de las migraciones para tener el catálogo Sunrise Sunset activo.
--
-- ============================================
