[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["npm cache clean --force", "rm -rf node_modules/.vite", "npm install", "npm run build"]

[start]
cmd = "npx serve dist -s -p ${PORT:-8080}"
