-- ============================================
-- SUNRISE SUNSET — USUARIOS DE PRUEBA
-- ============================================
--
-- Este archivo está vacío intencionalmente. Sunrise Sunset crea sus usuarios
-- a través del flujo de registro normal (/api/auth/register) o vía el
-- onboarding del estudio. No hay usuarios "de prueba" pre-seedeados en producción.
--
-- Si necesitas un admin local para desarrollo, regístrate por la UI
-- (/register) y promueve tu rol a 'admin' con:
--
--   UPDATE users SET role = 'admin' WHERE email = 'tu-email@ejemplo.com';
--
-- ============================================
